name: terraform-branches

on:
  push:
    branches-ignore:
      - master

jobs:
  deploy:
    name: Deployment Dev
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.MYKEY }}
        aws-secret-access-key: ${{ secrets.MYSECRET }}
        aws-region: ap-southeast-2

    - name: Terragrunt
      run: |
        wget -O ~/terragrunt https://github.com/gruntwork-io/terragrunt/releases/download/v0.36.10/terragrunt_linux_amd64
        chmod +x ~/terragrunt
        export PATH=$PATH:~/
        cd ./dev
        echo Branch ${GITHUB_REF##*/}
        terragrunt init
        terragrunt apply -auto-approve

      # optional teardown here or re-deploy any long lived dev branch in prod workflow (after master merge)
