name: terraform-branches

on:
  push:
    branches-ignore:
      - master

jobs:
  deploy:
    name: Deployment Dev
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.MYKEY }}
        aws-secret-access-key: ${{ secrets.MYSECRET }}
        aws-region: ap-southeast-2

    - name: Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_wrapper: false

    - name: Apply
      run: |
        cd ./dev
        terraform init -reconfigure
        terraform apply -auto-approve -var bucket_name=craigtfdev
